// ********RoostGPT********
/*
Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=
ROOST_METHOD_SIG_HASH=




*/

// ********RoostGPT********
using System;
using Xunit;
using Bunit;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Routing;
using System.Linq;
using MyBlazorApp.Components;

public class NavMenuTests : TestContext
{
    [Fact]
    public void NavMenuComponentRendersCorrectly()
    {
        // Arrange
        var cut = RenderComponent<NavMenu>();

        // Assert
        Assert.NotNull(cut.Find(".top-row"));
        Assert.Equal(3, cut.FindAll(".nav-item").Count);
        cut.Find(".navbar-toggler");
    }

    [Fact]
    public void ToggleNavMenuChangesCollapseState()
    {
        // Arrange
        var cut = RenderComponent<NavMenu>();

        // Act
        cut.Find(".navbar-toggler").Click();

        // Assert
        Assert.Null(cut.Instance.NavMenuCssClass);
    }

    [Fact]
    public void NavLinkNavigatesToCorrectPageOnClick()
    {
        // Arrange
        var cut = RenderComponent<NavMenu>();

        // Act
        var link = cut.FindAll("NavLink").Last();
        link.Click();

        // Assert
        Assert.Equal("weather", ((NavLink)link).href);
    }
}
