// ********RoostGPT********
/*
Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=
ROOST_METHOD_SIG_HASH=




*/

// ********RoostGPT********
using Xunit;
using Bunit;
using Microsoft.AspNetCore.Components;
using MyBlazorApp.Components;

public class CounterComponentTests : TestContext
{
    [Fact]
    public void CounterComponentRendersCorrectly()
    {
        // Arrange
        var cut = RenderComponent<Counter>();

        // Assert
        cut.MarkupMatches(
            "<h1>Counter</h1>" +
            "<p role=\"status\">Current count: 0</p>" +
            "<button class=\"btn btn-primary\">Click me</button>");
    }
    
    [Fact]
    public void CounterComponentIncrementsCountOnClick()
    {
        // Arrange
        var cut = RenderComponent<Counter>();
        
        // Act
        cut.Find("button").Click();
        
        // Assert
        cut.Find("p").MarkupMatches("<p role=\"status\">Current count: 1</p>");
    }

    [Fact]
    public void CounterComponentHandlesMultipleClicks()
    {
        // Arrange
        var cut = RenderComponent<Counter>();

        // Act
        var button = cut.Find("button");
        button.Click();
        button.Click();
        button.Click();

        // Assert
        cut.Find("p").MarkupMatches("<p role=\"status\">Current count: 3</p>");
    }
}
