// ********RoostGPT********
/*
Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=
ROOST_METHOD_SIG_HASH=




*/

// ********RoostGPT********
using System;
using Bunit;
using Bunit.Rendering;
using Microsoft.AspNetCore.Components;
using MyBlazorApp.Layout;
using Xunit;

namespace MyBlazorApp.Tests
{
    public class MainLayoutTest : TestContext
    {
        [Fact]
        public void MainLayoutRendersCorrectly()
        {
            // Arrange
            var cut = RenderComponent<MainLayout>();

            // Assert
            cut.MarkupMatches(@"
                <div class='page'>
                    <div class='sidebar'>
                        <NavMenu></NavMenu>
                    </div>
                    <main>
                        <div class='top-row px-4'>
                            <a href='https://learn.microsoft.com/aspnet/core/' target='_blank'>About</a>
                        </div>
                        <article class='content px-4'>
                            <!-- TODO: Replace with actual Body content -->
                        </article>
                    </main>
                </div>");
        }

        [Fact]
        public void MainLayoutBodyRendersChildContent()
        {
            // Arrange
            var cut = RenderComponent<MainLayout>(parameters => parameters.Add(p => p.Body, "Child Content"));

            // Assert
            cut.Find("article.content.px-4").MarkupMatches("<article class='content px-4'>Child Content</article>");
        }

        [Fact]
        public void MainLayoutNavMenuExists()
        {
            // Arrange
            var cut = RenderComponent<MainLayout>();

            // Assert
            cut.Find("div.sidebar NavMenu");
        }
    }
}
