// ********RoostGPT********
/*
Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=
ROOST_METHOD_SIG_HASH=




*/

// ********RoostGPT********
using System;
using Bunit;
using Microsoft.AspNetCore.Components;
using Xunit;

namespace Tests
{
    public class ComponentTests : TestContext
    {
        [Fact]
        public void ComponentRendersCorrectly()
        {
            var cut = RenderComponent<Component>();

            cut.MarkupMatches(@"
              <div class=""page"">
                  <div class=""sidebar"">
                      <NavMenu />
                  </div>

                  <main>
                      <div class=""top-row px-4"">
                          <a href=""https://learn.microsoft.com/aspnet/core/"" target=""_blank"">About</a>
                      </div>

                      <article class=""content px-4"">
                      </article>
                  </main>
              </div>");
        }

        [Fact]
        public void ComponentRendersBodyParameter()
        {
            var cut = RenderComponent<Component>(parameters => parameters
                .Add(p => p.Body, "test content"));

            cut.Find("article.content").TextContent.MarkupMatches("test content");
        }

        [Fact]
        public void ComponentBodyParameterCanBeChanged()
        {
            var cut = RenderComponent<Component>(parameters => parameters
                .Add(p => p.Body, "initial content"));

            cut.Find("article.content").TextContent.MarkupMatches("initial content");

            cut.SetParametersAndRender(parameters => parameters
                .Add(p => p.Body, "changed content"));

            cut.Find("article.content").TextContent.MarkupMatches("changed content");
        }
    }
}
