// ********RoostGPT********
/*
Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=
ROOST_METHOD_SIG_HASH=




*/

// ********RoostGPT********
using Bunit;
using Xunit;
using MyBlazorApp.Pages;
using Microsoft.AspNetCore.Components;

namespace MyBlazorApp.Tests
{
    public class HomeComponentTest : TestContext
    {
        [Fact(DisplayName = "Component Rendering")]
        public void CheckComponentIsCorrectlyRendered()
        {
            // Act
            var cut = RenderComponent<Home>();

            // Assert
            cut.MarkupMatches("<h1>Hello, world!</h1><p>Welcome to your new app.</p>");
        }
    }
}
