// ********RoostGPT********
/*
Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=
ROOST_METHOD_SIG_HASH=




*/

// ********RoostGPT********
using Xunit;
using Bunit;
using MyBlazorApp;

public class HomeComponentTest : IDisposable
{
    private readonly TestContext _context;

    public HomeComponentTest() 
    {
        _context = new TestContext();
    }

    [Fact]
    [Trait("Category", "rendering")]
    public void HomeComponentRendersCorrectly()
    {
        // Arrange
        var cut = _context.RenderComponent<Home>();

        // Act
        // Nothing to act upon as no interaction is required.

        // Assert
        cut.MarkupMatches("<h1>Hello, world!</h1>Welcome to your new app.");
    }

    // TODO: Generate additional tests for more complex components with parameters and events.

    // Dispose context
    public void Dispose() 
    {
        _context.Dispose();
    }
}
