// ********RoostGPT********
/*
Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=
ROOST_METHOD_SIG_HASH=




*/

// ********RoostGPT********
using Bunit;
using Bunit.Rendering;
using Bunit.TestDoubles;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.AspNetCore.Components.Routing;
using Xunit;
using MyBlazorApp;

namespace MyBlazorAppTests
{
    public class RouterTests : TestContext
    {
        [Fact]
        public void RouterComponentRendersCorrectly_WhenRouteDataExists()
        {
            // Arrange
            Services.AddTestAuthorization();
            Services.AddMockNavigationManager();
            var routeData = new RouteData(typeof(MainLayout));

            // Act
            var cut = RenderComponent<Router>(
                ("AppAssembly", typeof(App).Assembly),
                ("RouteData", routeData)
            );

            // Assert
            cut.Find("div.main-layout").HasChildNodes.ShouldBeTrue();
        }

        [Fact]
        public void RouterComponentDisplaysNotFoundPage_WhenRouteDataEmpty()
        {
            // Arrange
            Services.AddTestAuthorization();
            Services.AddMockNavigationManager();

            // Act
            var cut = RenderComponent<Router>(
                ("AppAssembly", typeof(App).Assembly)
            );

            // Assert
            cut.Find("p").MarkupMatches("<p role=\"alert\">Sorry, there's nothing at this address.</p>");
        }

        [Fact]
        public void RouterComponentUpdatesTitle_WhenRouteDataEmpty()
        {
            // Arrange
            Services.AddTestAuthorization();
            Services.AddMockNavigationManager();

            // Act
            var cut = RenderComponent<Router>(
                ("AppAssembly", typeof(App).Assembly)
            );

            // Assert
            cut.Find("h1").MarkupMatches("<h1>Not found</h1>");
        }
    }
}
