// ********RoostGPT********
/*
Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=
ROOST_METHOD_SIG_HASH=




*/

// ********RoostGPT********
using System;
using Bunit;
using Microsoft.AspNetCore.Components;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using MyBlazorApp.Layouts;
using Moq;
using Xunit;

public class MainLayoutTest : TestContext
{
    [Fact]
    public void CheckInitialRenderWithCollapsedNavMenu()
    {
        // Act
        var cut = RenderComponent<MainLayout>();

        // Assert
        cut.MarkupMatches(@"<div class=""top-row ps-3 navbar navbar-dark"">
                                <div class=""container-fluid"">
                                    <a class=""navbar-brand"" href="""">MyBlazorApp</a>
                                    <button title=""Navigation menu"" class=""navbar-toggler"">
                                        <span class=""navbar-toggler-icon""></span>
                                    </button>
                                </div>
                            </div>
                            <div class=""collapse nav-scrollable"">
                                <!-- Remaining markup omitted for brevity -->
                            </div>");
    }

    [Fact]
    public void CheckToggleNavMenuEvent()
    {
        // Act
        var cut = RenderComponent<MainLayout>();
        var button = cut.Find("button.navbar-toggler");
        button.Click();

        // Assert
        Assert.Contains("navbar-toggler", cut.Markup);
        Assert.DoesNotContain("collapse", cut.Markup);
    }

    [Fact]
    public void CheckNavMenuLinks()
    {
        // Act
        var cut = RenderComponent<MainLayout>();

        // Assert
        Assert.Contains("Home", cut.Markup);
        Assert.Contains("href=\"\"", cut.Markup);
        Assert.Contains("Counter", cut.Markup);
        Assert.Contains("href=\"counter\"", cut.Markup);
        Assert.Contains("Weather", cut.Markup);
        Assert.Contains("href=\"weather\"", cut.Markup);
    }
}
